apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: default
  labels:
    app: configserver
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: configserver
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
      - name: configserver
        image: jinsa05/configserver:0.0.1-SNAPSHOT
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        ports:
        - containerPort: 8071
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: default
spec:
  selector:
    app: configserver
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: configserver
    protocol: TCP
    port: 8071
    targetPort: 8071
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.

